export const appConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',

    GET_ALL_PROFILE_REQUEST: 'GET_ALL_PROFILE_REQUEST',
    GET_ALL_PROFILE_SUCCESS: 'GET_ALL_PROFILE_SUCCESS',
    GET_ALL_PROFILE_FAILURE: 'GET_ALL_PROFILE_FAILURE',

    GET_MY_PROFILE_REQUEST: 'GET_MY_PROFILE_REQUEST',
    GET_MY_PROFILE_SUCCESS: 'GET_MY_PROFILE_SUCCESS',
    GET_MY_PROFILE_FAILURE: 'GET_MY_PROFILE_FAILURE',
}